### PR TITLE
Removed Django version check for 1.8+ in runtests.py

### PR DESCRIPTION
**Pull request by atombrella**

### CODE REVIEW

**Comment by atombrella** [comment]
I'm not sure how to make Travis be green. The replaced code is a tautology, as the tests run only under Django 1.8+.

**Comment by spookylukey** [comment]
Thanks for the PR. I'm guessing there has been some change on Travis that is causing the builds to fail (e.g. different Firefox version or something), probably won't be that easy to debug...

**Comment by atombrella** [comment]
@spookylukey Closed by accident, could you please reopen?

**Comment by spookylukey** [comment]
It looks like I'm unable to re-open, but I will merge this once I've found a way to fix the build.

**Pull request closed without merging**
